### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [lmergner/contrivers-cms#1]
check out the database architecture within [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo), it may be easier to use ;)

**Comment by lmergner** [comment]
@vitaly-t I did look at the demo app. And I think my current design mirrors the layout that your propose in the examples. In the last 5 days, I'v evolved from `pg` to `pg-promise` to `knex` back to `pg` and finally `pg-promise`. At the same time, learning a great deal about Promises in Javascript, translating into async / await. Things are a bit of a mess. I pushed to github only to see if travis-ci worked.

I appreciate how proactive you are on Stack Overflow and Github. I am persuaded by your argument that promisifying pg does no good at a high level. Though I can't find much documentation about how node-postgres (or pg-promise) handle connection pooling. (I'm used to the very detailed documentation of [SQLAlchemy](http://www.sqlalchemy.org/).) For example, if I import and instantiate pgp in different files, is this sharing a pool "under the hood." When is a connection released back to the pool? 

A second question is how to handle many-to-many relationship joins. I'm not familiar enough with SQL to know if I can join a subquery for M2M, or if it's preferred to issue a second query (as SQLAlchemy does). In the latter case, I'm not understanding how `pg-promise` uses transactions. When I wrap two queries in a `db.tx` and a `Promise.all`, it's not working as I expected. On the other hand, since I'm only issuing two simple queries, maybe I shouldn't be using a transaction block. In any case, there are very few examples in the docs of how to handle complex relationships. I've got several adjacency joins (or what SQLAlchemy calls [polymorphic](http://docs.sqlalchemy.org/en/latest/orm/inheritance.html)).

Finally, I'm curious about your decision to bundle QueryFiles with pg-promise. Coming from Python, I'm used to larger libraries. However, node developers seem content to distributed "packages" of ~10 LOC. Considering that pg-monitor is a separate package, why not distribute QueryFiles independent of pg-promise?

And, not that this is your job, but if you have specific suggestions or criticisms, I'm happy to listen.

**Comment by vitaly-t** [comment]
That's a lot of questions :)

I've tried to document everything, the the project's website. If you are stuck on something - use StackOverflow ;)

**Comment by vitaly-t** [comment]
>Though I can't find much documentation about how node-postgres (or pg-promise) handle connection pooling

Yes, there is little about it within the node-postgres driver, and pg-promise is simply using what's there. Reading the code in `node-postgres` driver is one good approach. I cannot make any improvements in `node-posgres`, it is not my project, and the author isn't very receptive, to say the least, I've tried, he banned my account.

>I'm not understanding how pg-promise uses transactions.

There are many examples for correct transaction usage, starting with [Transactions](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#transactions).

>I'm curious about your decision to bundle QueryFiles with pg-promise

QueryFiles was designed specifically as part of the library, it has no value outside of the query.

If there were ongoing issues, it would have some weight, but given that there are 0 bugs known, no point now separating things just for the sake of doing it.

I did separate many things as it is - [spex](https://github.com/vitaly-t/spex) and [pg-minify](https://github.com/vitaly-t/pg-minify), because they are reusable.

**Comment by lmergner** [comment]
Thanks for the details. I ended up refactoring things to look more like the `pg-promises-demo`. It just took me awhile to get there.

**Comment by vitaly-t** [comment]
As for `promise.all`, and why you can't use it: [Why use method batch instead of promise.all?](https://github.com/vitaly-t/pg-promise/wiki/FAQ#why-use-method-batch-instead-of-promiseall)

**Comment by vitaly-t** [comment]
Also, there a few new things that `pg-promise-demo` doesn't cover at all. Primarily - namespaces [helpers](http://vitaly-t.github.io/pg-promise/helpers.html) and [utils](http://vitaly-t.github.io/pg-promise/utils.html).

**Comment by lmergner** [comment]
I think if connection pooling was better documented, and perhaps better understood, the need for a lower level promise solution -- as you've advocated for -- would be more apparent. Personally, I wish I had to the time to understand all this better.

**Comment by vitaly-t** [comment]
@lmergner you cab write much better code than here: https://github.com/lmergner/contrivers-cms/blob/master/api/routes.js

by using the methods and types available in the [helpers namespace](http://vitaly-t.github.io/pg-promise/helpers.html) ;)
